;;; opentelemetry/proto/collector/trace/v1/trace_service.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.TRACE.V1")
    (cl:defpackage "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.TRACE.V1" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.TRACE.V1-RPC")
    (cl:defpackage "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.TRACE.V1-RPC" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.TRACE.V1")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'trace_service
    :syntax :proto3

    :package "opentelemetry.proto.collector.trace.v1"
    :import '("opentelemetry/proto/trace/v1/trace.proto"))
)


;;; Top-Level messages

(pi:define-message export-trace-service-request
    ()
  ;; Fields
  (resource-spans
   :index 1 :type cl-protobufs.opentelemetry.proto.trace.v1::resource-spans :kind :message :label (:repeated :list) :field-presence :implicit :json-name "resourceSpans"))

(pi:define-message export-trace-service-response
    ()
  ;; Fields
  (partial-success
   :index 1 :type export-trace-partial-success :kind :message :label (:optional) :field-presence :explicit :json-name "partialSuccess"))

(pi:define-message export-trace-partial-success
    ()
  ;; Fields
  (rejected-spans
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :field-presence :implicit :json-name "rejectedSpans")
  (error-message
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "errorMessage"))

;;; Services
(pi:define-service trace-service
    (:source-location #P"opentelemetry/proto/collector/trace/v1/trace_service.proto")
  (export (
    export-trace-service-request =>
    export-trace-service-response)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:add-file-descriptor #P"opentelemetry/proto/collector/trace/v1/trace_service.proto" 'trace_service)
)

(cl:export '(error-message
export-trace-partial-success
export-trace-service-request
export-trace-service-response
partial-success
rejected-spans
resource-spans
trace-service
trace_service))

(cl:in-package "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.TRACE.V1-RPC")

(cl:export '(call-export
export))
