services:
  # OpenTelemetry collector for development. Spins up an otel collector and grafana.
  grafana-otel-lgtm:
    ports:
      - "3000:3000"
      - "4318:4318"
    image: "docker.io/grafana/otel-lgtm"
