;;; opentelemetry/proto/collector/logs/v1/logs_service.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.LOGS.V1")
    (cl:defpackage "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.LOGS.V1" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.LOGS.V1-RPC")
    (cl:defpackage "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.LOGS.V1-RPC" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.LOGS.V1")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'logs_service
    :syntax :proto3

    :package "opentelemetry.proto.collector.logs.v1"
    :import '("opentelemetry/proto/logs/v1/logs.proto"))
)


;;; Top-Level messages

(pi:define-message export-logs-service-request
    ()
  ;; Fields
  (resource-logs
   :index 1 :type cl-protobufs.opentelemetry.proto.logs.v1::resource-logs :kind :message :label (:repeated :list) :field-presence :implicit :json-name "resourceLogs"))

(pi:define-message export-logs-service-response
    ()
  ;; Fields
  (partial-success
   :index 1 :type export-logs-partial-success :kind :message :label (:optional) :field-presence :explicit :json-name "partialSuccess"))

(pi:define-message export-logs-partial-success
    ()
  ;; Fields
  (rejected-log-records
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :field-presence :implicit :json-name "rejectedLogRecords")
  (error-message
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "errorMessage"))

;;; Services
(pi:define-service logs-service
    (:source-location #P"opentelemetry/proto/collector/logs/v1/logs_service.proto")
  (export (
    export-logs-service-request =>
    export-logs-service-response)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:add-file-descriptor #P"opentelemetry/proto/collector/logs/v1/logs_service.proto" 'logs_service)
)

(cl:export '(error-message
export-logs-partial-success
export-logs-service-request
export-logs-service-response
logs-service
logs_service
partial-success
rejected-log-records
resource-logs))

(cl:in-package "CL-PROTOBUFS.OPENTELEMETRY.PROTO.COLLECTOR.LOGS.V1-RPC")

(cl:export '(call-export
export))
