services:
  common-lisp:
    build:
      context: ../../
      dockerfile: example/Dockerfile
    command: /app/tiny-routes
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/"]
      interval: "3s"
      timeout: "3s"
      retries: 3
      start_period: 40s
      start_interval: 5s
