name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: 40ants/setup-lisp@v4
        with:
          roswell-version: v24.10.115
          qlot-version: 1.6.0
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: cl-opentelemetry

      - name: Run tests
        shell: bash
        run: |
          export PATH=$PATH:$HOME/.roswell/bin
          qlot exec ros run -s cl-opentelemetry -e '(asdf:test-system :cl-opentelemetry)' -- --non-interactive

  oats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: jdx/mise-action@v2

      - run: docker compose build
        working-directory: example
      - run: oats .
        working-directory: example
