name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - uses: actions/checkout@v4
        with:
          submodules: true

      - run: earthly --ci +test
      - run: earthly --ci +test-proto

  oats:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: jdx/mise-action@v2

      - run: docker compose -f example/clack/compose.yaml build

      - run: oats example
