name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          set -eu

          apt update && apt install -y protobuf-compiler libprotobuf-dev
          earthly --ci --output +protobuf-build
          sudo install protoc-gen-cl-pb /usr/local/bin

      - uses: 40ants/setup-lisp@v4
        with:
          roswell-version: v24.10.115
          qlot-version: 1.6.0
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: cl-opentelemetry

  oats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: jdx/mise-action@v2

      - run: docker compose build
        working-directory: example
      - run: oats .
        working-directory: example
